### PR TITLE
added third argument to cmd line so users can uniquely identify themselv...

### PR DESCRIPTION
**Pull request by swam92**
okay here it is

### CODE REVIEW

**Comment by NoonienSoong** [comment]
So it works on local network. I was thinking setting up the server on a computer in the acm room. so we could chat while on campus. Or try and host it in the cloud, what do you think?

**Comment by swam92** [comment]
I have a raspberry pi.  Let's set up the server on that.  I think it would
be pretty cool..

**Comment by NoonienSoong** [comment]
Ya im totally down

**Comment by swam92** [comment]
Sweet.  will that require ssh'ing into the pi?

**Pull request merged**
